name: Deploy AWS SRE

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      # 📥 Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # 🔐 Configurar AWS
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 🐳 Login no ECR
      - name: Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPOSITORY

      # 🐳 Build Docker (AMD64)
      - name: Build Docker
        run: |
          docker buildx build --platform linux/amd64 -t sre-app --load ./app

      # 🔖 Tag da imagem
      - name: Tag Image
        run: |
          docker tag sre-app:latest $ECR_REPOSITORY:latest

      # 📦 Push para ECR
      - name: Push Image
        run: |
          docker push $ECR_REPOSITORY:latest

      # 🔧 Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 🚀 Terraform Apply (quando push OU botão apply)
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' || github.event_name == 'push' }}
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      # 💣 Terraform Destroy (quando botão destroy)
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: terraform
        run: |
          terraform init
          terraform destroy -auto-approve